version: "3.8"

services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: n8n-cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: <insert token>
    networks:
      - n8n_net


  postgres:
    image: postgres:16-alpine
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: <insert password>
      TZ: Europe/Copenhagen
    volumes:
      - /local/docker/n8n/postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    environment:
      # Basic
      TZ: Europe/Copenhagen
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: <insert webhookurl>

      # Database (Postgres)
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: <insert password>

      # Security / hygiene
      N8N_ENCRYPTION_KEY: <insert encryptionkey>
      N8N_SECURE_COOKIE: "false"

      # Optional logging
      N8N_LOG_LEVEL: info

      # Later (when you add reverse proxy / tunnel), youâ€™ll change these:
      # N8N_HOST: n8n.yourdomain.com
      # N8N_PROTOCOL: https
      # WEBHOOK_URL: https://n8n.yourdomain.com/
    volumes:
      - /local/docker/n8n/n8n_data:/home/node/.n8n
    networks:
      - n8n_net

networks:
  n8n_net:
    driver: bridge
